---
env: SKIP_INTERPRETER=true

language: python
python: 
  - "3.7.3"
  - "3.8.1"

env:
  - DATABASE_URL="postgresql://postgres:@localhost/travis_ci_test"
services: 
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
install: 
  - "pip install -r src/requirements.txt"
  - pip install tox-travis
  - "python src/create_db.py"


script:
  - tox
